// Material 3 dark color tokens for LifeOS (cyan primary, dark surfaces).
// Kept in sync with src/theme/paperTheme.ts and
// android/app/src/main/res/values/colors.xml.
export const material3Dark = {
  primary: '#4DB8FF',
  onPrimary: '#0B0E14',
  primaryContainer: '#004D80',
  onPrimaryContainer: '#B8E6FF',
  secondary: '#8B5CF6',
  onSecondary: '#FFFFFF',
  secondaryContainer: '#3B1F8C',
  onSecondaryContainer: '#DDD6FE',
  tertiary: '#38BDF8',
  onTertiary: '#0B0E14',
  tertiaryContainer: '#004D80',
  onTertiaryContainer: '#B8E6FF',
  surface: '#0B0E14',
  onSurface: '#FFFFFF',
  surfaceVariant: '#141A25',
  onSurfaceVariant: '#9CA3AF',
  outline: '#2A303C',
  outlineVariant: '#1F2937',
  error: '#FF6B6B',
  onError: '#0B0E14',
  errorContainer: '#8C1D18',
  onErrorContainer: '#F9DEDC',
  surfaceTint: '#4DB8FF',
  inverseSurface: '#E6E0E9',
  inverseOnSurface: '#0B0E14',
  inversePrimary: '#4DB8FF',
  scrim: '#000000',
  shadow: '#000000',
} as const;

// Map our existing semantic color names to Material 3 roles so existing
// screens can be restyled with minimal changes.
export const material3Semantic = {
  bgPrimary: material3Dark.surface,
  bgSecondary: material3Dark.surfaceVariant,
  bgElevated: material3Dark.surfaceVariant,
  bgTertiary: material3Dark.surfaceVariant,
  glassWhite: material3Dark.surfaceVariant,
  glassWhiteStrong: material3Dark.surfaceVariant,
  glassBlack: 'rgba(0,0,0,0.6)',
  border: material3Dark.outlineVariant,
  borderSubtle: material3Dark.outlineVariant,
  textPrimary: material3Dark.onSurface,
  textSecondary: material3Dark.onSurfaceVariant,
  textTertiary: material3Dark.outline,
  textInverse: material3Dark.onPrimaryContainer,
  textOnAccent: material3Dark.onPrimary,
  accentPrimary: material3Dark.primary,
  accentSecondary: material3Dark.secondary,
  accentTertiary: material3Dark.tertiary,
  success: '#7BC47B',
  warning: '#F5CB5C',
  danger: material3Dark.error,
  info: '#7FC8F8',
  category: {
    food: '#F5CB5C',
    transport: '#7FC8F8',
    utilities: '#D0BCFF',
    groceries: '#7BC47B',
    rent: '#F2B8B5',
    airtime: '#67D4E0',
    entertainment: '#EFB8C8',
    health: '#F5CB5C',
    education: '#B8C2FF',
    shopping: '#EFB8C8',
    savings: '#7BC47B',
    investment: '#67D4E0',
    income: '#7BC47B',
    uncategorized: material3Dark.onSurfaceVariant,
  },
  priority: {
    low: '#7FC8F8',
    medium: '#F5CB5C',
    high: '#F2B8B5',
  },
} as const;

export type Material3Colors = typeof material3Semantic;
