import { MD3DarkTheme, MD3LightTheme, type MD3Theme } from 'react-native-paper';

// Custom Material 3 theme for the LifeOS preview.
// Modern reskin: neutral (untinted) near-black surfaces, a single refined
// accent, soft corner radii, and a tighter/heavier headline scale. The goal is
// a contemporary fintech feel while keeping Paper's components and behavior.
export const lifeosPaperTheme: MD3Theme = {
  ...MD3DarkTheme,
  dark: true,
  version: 3,
  isV3: true,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#57B9FF',
    onPrimary: '#0A0A0B',
    primaryContainer: '#0F2A40',
    onPrimaryContainer: '#BFE3FF',
    secondary: '#A1A1AA',
    onSecondary: '#0A0A0B',
    secondaryContainer: '#26272B',
    onSecondaryContainer: '#E4E4E7',
    tertiary: '#5EEAD4',
    onTertiary: '#0A0A0B',
    tertiaryContainer: '#0F3A33',
    onTertiaryContainer: '#CCFBF1',
    surface: '#0A0A0B',
    surfaceVariant: '#161618',
    background: '#0A0A0B',
    onSurface: '#F4F4F5',
    onSurfaceVariant: '#A1A1AA',
    outline: '#2E2E33',
    outlineVariant: '#222226',
    error: '#F87171',
    onError: '#0A0A0B',
    errorContainer: '#3A1214',
    onErrorContainer: '#FECACA',
    inverseSurface: '#F4F4F5',
    inverseOnSurface: '#0A0A0B',
    inversePrimary: '#57B9FF',
    elevation: {
      level0: 'transparent',
      level1: '#131315',
      level2: '#161618',
      level3: '#1A1A1D',
      level4: '#1D1D20',
      level5: '#212124',
    },
  },
  roundness: 6,
  fonts: {
    ...MD3DarkTheme.fonts,
    headlineLarge: {
      ...MD3DarkTheme.fonts.headlineLarge,
      fontSize: 30,
      lineHeight: 36,
      fontWeight: '700',
      letterSpacing: -0.5,
    },
    headlineMedium: {
      ...MD3DarkTheme.fonts.headlineMedium,
      fontSize: 24,
      lineHeight: 30,
      fontWeight: '700',
      letterSpacing: -0.4,
    },
    headlineSmall: {
      ...MD3DarkTheme.fonts.headlineSmall,
      fontSize: 20,
      lineHeight: 26,
      fontWeight: '700',
      letterSpacing: -0.3,
    },
    titleLarge: {
      ...MD3DarkTheme.fonts.titleLarge,
      fontSize: 18,
      lineHeight: 24,
      fontWeight: '600',
      letterSpacing: -0.2,
    },
    titleMedium: {
      ...MD3DarkTheme.fonts.titleMedium,
      fontSize: 16,
      lineHeight: 22,
      fontWeight: '600',
    },
    labelLarge: {
      ...MD3DarkTheme.fonts.labelLarge,
      fontWeight: '600',
    },
  },
};

export const lifeosPaperThemeLight: MD3Theme = {
  ...MD3LightTheme,
  dark: false,
  version: 3,
  isV3: true,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#0369A1',
    onPrimary: '#FFFFFF',
    primaryContainer: '#BAE6FD',
    onPrimaryContainer: '#082F49',
    secondary: '#64748B',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#E2E8F0',
    onSecondaryContainer: '#1E293B',
    tertiary: '#0F766E',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#CCFBF1',
    onTertiaryContainer: '#134E4A',
    surface: '#F8FAFC',
    surfaceVariant: '#EEF2F7',
    background: '#E8EDF3',
    onSurface: '#0F172A',
    onSurfaceVariant: '#475569',
    outline: '#CBD5E1',
    outlineVariant: '#E2E8F0',
    error: '#DC2626',
    onError: '#FFFFFF',
    errorContainer: '#FEE2E2',
    onErrorContainer: '#7F1D1D',
    inverseSurface: '#1E293B',
    inverseOnSurface: '#F8FAFC',
    inversePrimary: '#7DD3FC',
    elevation: {
      level0: 'transparent',
      level1: '#F8FAFC',
      level2: '#F1F5F9',
      level3: '#E2E8F0',
      level4: '#CBD5E1',
      level5: '#94A3B8',
    },
  },
  roundness: 6,
  fonts: {
    ...MD3LightTheme.fonts,
    headlineLarge: {
      ...MD3LightTheme.fonts.headlineLarge,
      fontSize: 30,
      lineHeight: 36,
      fontWeight: '700',
      letterSpacing: -0.5,
    },
    headlineMedium: {
      ...MD3LightTheme.fonts.headlineMedium,
      fontSize: 24,
      lineHeight: 30,
      fontWeight: '700',
      letterSpacing: -0.4,
    },
    headlineSmall: {
      ...MD3LightTheme.fonts.headlineSmall,
      fontSize: 20,
      lineHeight: 26,
      fontWeight: '700',
      letterSpacing: -0.3,
    },
    titleLarge: {
      ...MD3LightTheme.fonts.titleLarge,
      fontSize: 18,
      lineHeight: 24,
      fontWeight: '600',
      letterSpacing: -0.2,
    },
    titleMedium: {
      ...MD3LightTheme.fonts.titleMedium,
      fontSize: 16,
      lineHeight: 22,
      fontWeight: '600',
    },
    labelLarge: {
      ...MD3LightTheme.fonts.labelLarge,
      fontWeight: '600',
    },
  },
};
